language: python

python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  # After installing Vyper go back into the vyper-test directory
  - git clone https://github.com/ethereum/vyper.git; cd vyper; make; make test; cd ..;

# pytest should be pre-installed by Travis CI
script:
  - python3 -m pytest -v --color=yes --exitfirst --showlocals --durations=5

# safelist
branches:
  only:
  - master